dist: trusty
sudo: false
language: python
python:
  - "3.6"

addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main'
      - key_url: 'https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub'
    packages:
      - salt-common
      - rpm2cpio

install:
  - pip3 install coala coala-bears
  - wget http://download.opensuse.org/repositories/home:/SilvioMoioli:/tools/SLE_12_SP1/x86_64/terraform.rpm
  - rpm2cpio ./terraform.rpm | cpio -idmv
  - wget http://download.opensuse.org/repositories/home:/SilvioMoioli:/tools/SLE_12_SP1/x86_64/terraform-provider-libvirt.rpm
  - rpm2cpio ./terraform-provider-libvirt.rpm | cpio -idmv
  - export PATH=$PATH:$PWD/usr/bin/

before_script: terraform --version

script:
  - coala --ci
  - bash .ci-travis/terraform-validation
  - bash .ci-travis/salt-server-validation
  - bash .ci-travis/salt-client-validation
  - bash .ci-travis/salt-minion-validation
  - bash .ci-travis/salt-ctl-validation
