name: CI validation tests

on:
  pull_request:
    branches:
      - master

jobs:
  validate_salt:
    name: Validate Salt states
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: salt-common
        version: 1.0
    - name: Validate server states
      run: bash .github/workflows/ci-validation/salt-server-validation
    - name: Validate client states
      run: bash .github/workflows/ci-validation/salt-client-validation
    - name: Validate minion states
      run: bash .github/workflows/ci-validation/salt-minion-validation
    - name: Validate controller states
      run: bash .github/workflows/ci-validation/salt-controller-validation
    # TODO: Test more roles
